name: on-call
on:
  workflow_call:
  workflow_dispatch:

jobs:
  sign-rpm:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rpm-build and gnupg
        run: sudo apt install -y rpm gnupg
        
      - name: gpg to file
        run: echo "${{ secrets.MY_SECRET }}" > my_secret_file.asc

      - name: Set up GPG
        run: |
          cat my_secret_file.asc | gpg --batch --import
          gpg --list-keys
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Prepare RPM Signing Key
        run: |
          echo '%_signature gpg' >> ~/.rpmmacros
          echo '%_gpg_name aerospiketest' >> ~/.rpmmacros

      - name: Set GPG key trust
        run: echo ${{ secrets.GPG_PASSPHRASE }} | gpg --passphrase-fd 0 --pinentry-mode loopback --batch --import-ownertrust

      - name: Sign RPM
        run: rpmsign --define "_gpg_name AerospikeTest" --addsign app/your.rpm

      - name: Verify signed RPM
        run: rpmsign --verify app/your.rpm
