name: on-call
on:
  workflow_call:
  workflow_dispatch:

jobs:
  sign-rpm:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sign all RPM packages at Packages folder.
        uses: dante-signal31/rpmsign@v1.0.3
        with:
          gpg_private_key: "${{ secrets.GPG_P_K }}"
          gpg_private_key_password: ${{ vars.GPG_PASSPHRASE }}
          gpg_name: aerospiketest
          rpm_file: app/your.rpm
          output_folder: SignedPackages/
