name: on-call
on:
  workflow_call:
  workflow_dispatch:

jobs:
  sign-rpm:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rpm-build and gnupg
        run: sudo apt install -y rpm gnupg
      - name: Import GPG key
        run: |
          echo $GPG_PRIVATE_KEY | gpg --import --batch --yes
          echo -e "5\ny\n" | gpg --command-fd 0 --expert --edit-key <YOUR_KEY_ID> trust
        env:
          GPG_PRIVATE_KEY: ${{ vars.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ vars.GPG_PASSPHRASE }}       

      - name: Import GPG key
        run: echo ${{ vars.GPG_PRIVATE_KEY }} | gpg --import

      - name: Set GPG key trust
        run: echo ${{ vars.GPG_PASSPHRASE }} | gpg --passphrase-fd 0 --pinentry-mode loopback --batch --import-ownertrust

      - name: Prepare RPM Signing Key
        run: |
          echo '%_signature gpg' >> ~/.rpmmacros
          echo '%_gpg_name aerospiketest' >> ~/.rpmmacros

      - name: Set GPG key trust
        run: echo ${{ vars.GPG_PASSPHRASE }} | gpg --passphrase-fd 0 --pinentry-mode loopback --batch --import-ownertrust

      - name: Sign RPM
        run: rpmsign --define "_gpg_name AerospikeTest" --addsign app/your.rpm

      - name: Verify signed RPM
        run: rpmsign --verify app/your.rpm
